# action.yml
name: "AUR sync docker"
description: "Sync an AUR package with Github release"
author: maniacata
branding:
  color: green
  icon: refresh-cw
inputs:
  package_name:
    description: "AUR package name"
    required: true
  github_repo:
    description: "GitHub repo name"
    required: true
  commit_username:
    description: "The username to use when creating the new commit."
    required: true
  commit_email:
    description: "The email to use when creating the new commit."
    required: true
  ssh_private_key:
    description: "Your private key with access to AUR package."
    required: true
  extra_dependencies:
    description: "Extra dependencies when building AUR package."
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.package_name }}
    - ${{ inputs.github_repo }}
    - ${{ inputs.commit_username }}
    - ${{ inputs.commit_email }}
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.extra_dependencies }}
